name: pandoc-scdoc
version: 0.1.0.0
github: "smoge/pandoc-scdoc"
license: GPL-3.0-only
author: "smoge"
maintainer: "smoge <https://github.com/smoge>"
copyright: "2026 smoge"

extra-source-files:
  - README.md
  - CHANGELOG.md

data-files:
  - data/templates/default.schelp

description: Please see the README on GitHub at <https://github.com/smoge/pandoc-scdoc>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - doclayout
  - doctemplates
  - mtl
  - pandoc
  - pandoc-types
  - text

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  pandoc-scdoc:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pandoc-scdoc

tests:
  pandoc-scdoc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pandoc-scdoc
      - hspec >= 2.10
      - QuickCheck
      - containers
      - doctemplates
      - pandoc
      - directory
      - filepath
